# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0"

      - name: get version and echo to $GITHUB_ENV
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          echo "V_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo 'Env.VERSION: ${{env.VERSION}}'
          echo 'Env.V_VERSION: ${{env.V_VERSION}}'

      - name: Build
        run: dotnet build Publish.sln -c Release

      - name: Pack
        run: dotnet pack Publish.sln -c Release -o Publish -p:PackageVersion=${{env.VERSION}}

      - name: Push
        run: dotnet nuget push "Publish/*.${{env.VERSION}}.nupkg" --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_ORG_APIKEY }}
